import pathlib,json,csv,hashlib,collections
R=pathlib.Path(__file__).resolve().parents[2]
O=R/'Components/phase1_closure';O.mkdir(exist_ok=True)
sources=json.loads((R/'SOURCES/components/closure_2026-09-15/manifest.json').read_text())
src={s['id']:s for s in sources}
rows=[]
for r in csv.DictReader((R/'Components/Proposed_Operating_Component_Set.csv').open(encoding='utf-8-sig')):
    custom=r['phase1_disposition'].startswith('CUSTOM')
    rows.append(dict(id=r['set_id'],segment=r['segment'],function=r['required_function'],quantity=r['quantity'],manufacturer=r['manufacturer'],part=r['exact_identifier_or_project_part'],description=r['proposed_component'],status='CUSTOM/TO BE VERIFIED' if custom else 'CANDIDATE / EVIDENCE INCOMPLETE',sources=r['source_ids'].split('; '),order_url=r['order_url'],dimensions_mass=r['known_size_and_mass'],power=r['known_power_or_generation'],interfaces=r['functional_basis'],uncertainty=r['evidence_or_design_gap'],blocked=r['blocked_release_or_analysis'],cost=r['cost_and_availability'],rationale=r['functional_basis'],verification='Not procurement released. See linked earlier property matrix and custom work packages.',included_in=None))
def get(i):return next(r for r in rows if r['id']==i)
def edit(i,**kw):get(i).update(kw)
def add(i,fn,part,details,interfaces,verify,sources=None,included=None,manufacturer='DEGENERATE-1',status='CUSTOM/TO BE VERIFIED',dm='Design not released; dimensions and mass unknown',power='To be established from connected loads',cost='Not quoted; no purchase made',url='Custom fabrication; no order release'):
    rows.append(dict(id=i,segment='Ground' if i.startswith(('GND','SUP')) else 'Flight',function=fn,quantity='1 assembly/set unless explicitly noted',manufacturer=manufacturer,part=part,description=details,status=status,sources=sources or [],order_url=url,dimensions_mass=dm,power=power,interfaces=interfaces,uncertainty=verify,blocked='Integrated build/operation release until the stated verification is complete',cost=cost,rationale='Necessary to implement the existing Earth-image mission or safely connect, assemble and operate its hardware',verification=verify,included_in=included))
edit('GND-003',manufacturer='RIGOL',part='DP711',description='DP700-series programmable bench supply, US mains configuration',status='SUPPORTED',sources=['E13','E14','E40'],order_url=src['E40']['url'],dimensions_mass='140 x 202 x 332 mm; 6.9 kg',power='0–30 V, 0–5 A DC output; 150 W rated output. Selectable 100/120/220/240 V AC, 50–60 Hz; maximum input 400 VA.',interfaces='Front output terminals; RS-232. Use at 5 V upstream of GND-011, never as a direct AX100 3.3 V protection device.',uncertainty='US line setting/fuse must be inspected. Leads are a separate custom assembly. System protection belongs to GND-011.',blocked='No independent site or modem integration verification yet',cost='Current manufacturer product route; price not established',verification='Manufacturer ratings establish the supply component, not the protected modem installation. Check line selector/fuse, polarity, calibration and load behavior before connection.',rationale='Replaces unnamed supply with an exact documented model; separate regulation avoids reliance on slow/coarse bench OVP.')
edit('GND-004',status='SUPPORTED',sources=['E27'],order_url='https://www.m2inc.com/',dimensions_mass='Boom 18 ft 10 in; maximum element 13.25 in; antenna 7.5 lb (shipping 10 lb); mast interface 1.5–2 in',power='Passive 50-ohm antenna, 430–438 MHz; manufacturer catalog gain 18.9 dBic; not installed link evidence',interfaces='N-female feed. Manufacturer phasing lines and assembly hardware included; nonconductive mast/crossboom and clearance mandatory.',uncertainty='Authorized frequency, installed feed loss/pattern, site loads and tracking remain unverified integration properties.',blocked='Installed link and site acceptance',verification='Assemble to E27; inspect phasing/handedness; measure return loss and installed feed loss; verify site loads and pointing independently.',rationale='Exact existing antenna has a full assembly manual and parts list. No gain or mission performance upgraded.')
edit('GND-005',manufacturer='Yaesu',part='G-5500DC, 110–120 V AC controller configuration',description='Azimuth/elevation rotators and manual controller kit',status='SUPPORTED',sources=['E32'],order_url='https://www.yaesu.com/product-detail.aspx?CatName=Rotators&Model=G-5500DC',dimensions_mass='Rotators 8 kg; controller 3 kg. Mast diameter 38–63 mm; boom 32–43 mm; installation drawings in E32.',power='110–120 V AC selected regional controller; motors 22 V DC. Maximum continuous rotation 3 minutes; input current not established here.',interfaces='Two field control cables needed; supplied 7-pin connectors and 8-pin DIN interface. Computer interface is GND-012, not included.',uncertainty='Site loads, current/protection sizing and tracking duty remain installation acceptance items. Accuracy specification is ±4 percent, not ±4 degrees.',blocked='Automatic tracking and installed load acceptance',verification='Use E32 wiring and drawings; measure input demand for site protection; prove commanded limits, feedback calibration, duty and safe stop before mounting antenna.',rationale='Replaces unnamed rotator with a documented kit. Component support is conditional on published mechanical/duty limits; the selected antenna installation is not yet demonstrated.')
# Strictly retain this as incomplete because required input power is not published in the reviewed evidence.
edit('GND-005',status='CANDIDATE / EVIDENCE INCOMPLETE')
edit('GND-009',manufacturer='Raspberry Pi',part='Raspberry Pi 400 US Personal Computer Kit, 4 GB',description='Ground host, integrated keyboard; kit PSU/mouse/micro-HDMI cable and supplied card',sources=['E20','E41'],order_url=src['E41']['url'],dimensions_mass='286 x 122 x 23 mm; manufacturer mass absent from reviewed brief',power='USB-C 5 V; kit regional PSU included; exact PSU SKU and host maximum input/current not closed by reviewed brief',interfaces='USB 3.0 x2, USB 2.0 x1, Gigabit Ethernet, micro-HDMI. Raspberry Pi OS; actual modem/control software must be ported and demonstrated.',uncertainty='Mass, PSU exact identity/rating, deterministic recovery, storage endurance and modem software support incomplete.',blocked='Ground software, power and configuration release',cost='Manufacturer brief lists US kit USD 80 excluding tax; current delivered price/stock not guaranteed',rationale='Exact inexpensive free-software host proposal replaces unnamed PC; no claim that vendor modem software runs on it.')
edit('GND-010',manufacturer='Canon',part='SELPHY CP1500 US kit with CA-CP300B adapter and PCPL-CP400 paper cassette',description='Print reconstructed image from SD card; exact retail color/SKU not material to electrical function',status='SUPPORTED',sources=['E17','E18','E39','E48','E49'],order_url=src['E39']['url'],dimensions_mass='182.2 x 57.6 x 133 mm; approximately 850 g printer body. Paper travel clearance must follow manual.',power='Maximum printing 60 W; standby 4 W or less. Included adapter input 100–240 V AC 50/60 Hz; output 24 V DC, 1.8 A.',interfaces='SD/SDHC/SDXC card printing of supported JPEG/Exif images; USB-C is data, not charging. No Linux USB driver compatibility assumed.',uncertainty='Confirm regional kit contents at ordering; integrated image-format/read/print demonstration remains outstanding. Adapter rating and printer maximum are separate published statements.',blocked='End-to-end printed mission artifact not demonstrated',cost='Current US manufacturer order page; final delivered price not captured',verification='Test a reconstructed image and retain original bytes plus documented print derivative. Use included power supply and compatible paper/ink.',rationale='Direct SD printing avoids dependence on an unverified Linux print driver; exact manufacturer documentation covers the intended use.')
edit('GND-007',manufacturer='DEGENERATE-1',part='D1-GND-TR-001',description='Custom interlocked ground receive/transmit chain',status='CUSTOM/TO BE VERIFIED',sources=['E31','E42','E43','S10'],interfaces='AX100 RF port → fail-safe routing → filter/feedline/antenna; receive branch has documented LNA. Switching must precede and inhibit transmitter operation.',uncertainty='Schematic, exact switching/filter constituents, control logic and protection release absent; RC-2SPDT-A18 is a researched candidate, not approved.',verification='Create RF/control schematic and loss/noise/power budget, prove no transmit path into LNA under reset/power loss/single-control fault; measure isolation, sequencing, insertion loss and conducted emissions.',rationale='A genuine site-specific interlocked assembly is required; an LNA alone cannot provide two-way operation.')
add('GND-011','Protected modem DC conversion and supply leads','D1-GND-PWR-001','Custom 5 V input to regulated/protected avionics rail enclosure','DP711 output terminals to DMC-3 selected inputs; separate logic/USB power paths','Release regulator/eFuse/fuse exact ICs, schematic, wire/terminal BOM, enclosure, limits and test points. Prove all tolerance/load/transient/startup/fault states stay within AX100 voltage limits; demonstrate no USB backfeed. Bench OVP is not an adequate replacement.',['E13','E14','S10','S45'])
add('GND-012','Computer-to-rotator control, safe stop and feedback','D1-GND-CTRL-001','Custom controller/interface assembly','G-5500DC 8-pin DIN signals to isolated host interface','Release controller schematic, ADC/driver/isolator part numbers, connector pin map and enclosure. Demonstrate limits, watchdog, disconnected feedback, stalled motion, calibration and power-loss stop; verify manual override. GS-232B researched as COTS alternate but English documentation/configuration incomplete.',['E32','E16'])
add('GND-013','Rotator field wiring and weatherproof strain relief','D1-GND-ROT-HAR-001','Two field cables with supplied rotator connector kits','Six conductors per azimuth/elevation circuit per E32; length/site dependent','Release exact cable gauge/jacket, cores, shields if needed, terminal assignments, gland and support parts; calculate voltage drop from motor data and actual length, verify continuity/insulation/motion without snagging.',['E32'])
add('GND-014','Nonconductive antenna crossboom and conductor exclusion','D1-GND-BOOM-001','Custom glass-fiber or other justified nonconductive boom and clamps','M2 mast 1.5–2 in; Yaesu boom 32–43 mm: compatible clamp geometry must be designed, not assumed','Specify exact stock material and supplier, section, length and clamp hardware; no carbon-fiber substitution assumed nonconductive. Verify bending/torsion/fatigue/weathering, swept envelope and conductor exclusion. E27 requires at least 12 in element-tip clearance; rear coax loop approximately 60 in, reattach beyond clearance.',['E27','E32'])
add('GND-015','Receive low-noise gain','ZX60-P103LN+','Documented coaxial LNA; constituent of GND-007','SMA female 50 ohm RF ports; DC connector per manufacturer outline','No system sensitivity established; preserve case temperature and input limits. Transmit must never enter this branch. Verify actual frequency gain/noise and installed bias filtering.',['E31'],included='GND-007',manufacturer='Mini-Circuits',status='SUPPORTED',dm='23 g; body approximately 18.80 x 19.1 x 11.68 mm; connector envelope per E31 drawing',power='5 V DC; 95 mA typical, 120 mA maximum; maximum no-damage RF input 21 dBm in 50–2000 MHz range',url=src['E31']['url'])
add('GND-016','RF surge suppression at bonded entry','IS-50NX-C0','DC-blocking coax surge protector','50 ohm N-female both ends; 1.5–700 MHz','Verify installed bonding/entry enclosure and local code; no outdoor IP rating established. Not proof of lightning-safe installation.',['E28'],included='GND-008',manufacturer='PolyPhaser',status='SUPPORTED',dm='62.23 x 44.45 x 38.1 mm; 158.76 g',power='Passive; 125 W rating for 220–700 MHz; DC blocked',url='https://www.polyphaser.com/')
add('GND-017','Ground receive band selection and rejection','D1-GND-FILT-001','Custom filter assembly, frequency-dependent design','50 ohm RF chain; connector gender and location in GND-007 to be released','Specify licensed frequency and occupied bandwidth first; derive loss/rejection/power requirements from chosen waveform and local interferers. Release topology, exact resonator/LC parts, tuning instructions and enclosure; measure S parameters and power behavior. Not a fictional filter part.',['S10','E31'],included='GND-007')
add('GND-018','Station display','VA24EHF','Candidate 23.8-inch monitor with stand','HDMI 1.4 from Pi kit micro-HDMI cable','Regional power cord/configuration and operating environment not fully captured; confirm before admission.',['E44'],manufacturer='ASUS',status='CANDIDATE / EVIDENCE INCOMPLETE',dm='539.5 x 417.2 x 205.9 mm with stand; 2.84 kg',power='100–240 V AC 50/60 Hz; listed 12.02 W consumption; maximum demand not verified',url=src['E44']['url'])
add('GND-019','Removable image transfer and archival media','SDCIT2/32GB','Two Kingston industrial microSD cards with SD adapters proposed: transfer and backup','3.3 V microSD/SDHC FAT32; SD adapter for Canon','Mass and maximum operating current absent from reviewed datasheet. Confirm host/card/format compatibility and verify full written capacity; preserve checksums and backup independently. Supplied Pi boot card belongs to host kit, not this pair.',['E45','E49'],manufacturer='Kingston',status='CANDIDATE / EVIDENCE INCOMPLETE',dm='Card 11 x 15 x 1 mm; adapter 24 x 32 x 2.1 mm; mass unknown',power='3.3 V; maximum current not provided in reviewed source',url='https://www.kingston.com/en/memory-cards/industrial-grade-microsd-uhs-i-u3')
add('GND-020','Host-to-removable-card interface','SDMSDRWU3AC','USB-A/USB-C SD and microSD reader','USB bus power; SD/microSD UHS-I','Actual maximum current not established by reviewed page; host bus and media interoperability require verification.',['E30'],manufacturer='StarTech.com',status='CANDIDATE / EVIDENCE INCOMPLETE',dm='73 x 20 x 11 mm; 14 g',power='5 V USB bus powered; consumption unknown',url=src['E30']['url'])
add('GND-021','Printer ink and physical photo paper','RP-108','Compatible Canon ink/paper pack, 108 postcard-size sheets/prints','CP1500 with supplied PCPL-CP400 cassette','Manufacturer compatibility is established; pack mass and retail envelope not captured. Consumable dimensions other than print format are not mission-critical; do not infer cartridge substitution.',['E48'],manufacturer='Canon',status='CANDIDATE / EVIDENCE INCOMPLETE',dm='Postcard-format media; pack mass/envelope not established',power='Passive consumables',url='https://www.usa.canon.com/',cost='USD 39.99 observed indicative retail; tax/shipping excluded')
add('GND-022','Ground RF/weather enclosure and DC distribution','D1-GND-ENC-001','Custom protected modem/LNA/router enclosure set','GND-001/002/007/011, coax entries and site bond','Release exact enclosure, glands, seals, brackets, fused DC branches and thermal ventilation design; verify ingress, condensation, accessible service, touch safety and temperature. Mains must not be improvised inside an unapproved enclosure.',['E28','E31','S45'])
add('GND-023','Mains distribution, protective earth and shutdown','D1-GND-AC-001','Custom site installation using appropriately listed commercial electrical hardware','DP711, rotator, host PSU, display and printer supplied adapters','Define site jurisdiction/service, outlet type, breaker/RCD or GFCI as applicable, exact listed parts and cable ratings; load and fault/earthing review before energizing. No homemade mains PSU. Professional electrical work is external expertise and separately costed.',['E14','E17','E32'])
add('GND-024','Host data and network cabling','D1-GND-DATA-HAR-001','Custom length/configuration cable kit','USB host to DMC-3 and controller; Ethernet to existing network; display uses Pi kit cable','Release actual port/gender map, manufacturer cable SKUs, lengths, shielding and retention. Verify data recovery after disconnect/power cycle. Existing internet/router infrastructure is a required declared dependency, not included hardware.',['S45','E20'])
add('GND-025','RF switching hardware alternate under evaluation','RC-2SPDT-A18','Candidate dual absorptive RF switch, not yet selected constituent','SMA female; USB-B/Ethernet control; included AC/DC-24-3W1 supply','Datasheet says 960 g while drawing says 980 g; reconcile revision. Prove safe default, interlock and ratings before selection. Internal termination only 1 W; transmitter must be inhibited during switching.',['E42','E43'],manufacturer='Mini-Circuits',status='CANDIDATE / EVIDENCE INCOMPLETE',dm='4.5 x 6 x 2.25 in nominal body; 960/980 g conflict',power='24 V; up to 500 mA in stated switched condition; included mains adapter',url=src['E42']['url'],included='GND-007 alternative; not additional purchase')
add('FLT-020','Independent launch/handling hazard isolation','D1-SAFE-001','Custom safety integration, replacing reliance on an undefined EPS switch option','Battery, all solar sources, EGSE, separation actuators, RBF, RF and antenna release paths','Release fault tree, inhibit truth table and independently inspectable schematic. Choose exact switches with manufacturer travel/contact/environment evidence; Honeywell SE/XE researched but not admitted. Demonstrate no alternate feed path and correct reset/recovery. No architecture credit merely for three switches.',['S01','S03','S33','E12'])
edit('FLT-002',included_in='FLT-020; unresolved COTS actuator constituent, not an additional assembly')
edit('FLT-019',sources=['S01','S33'])
add('FLT-021','External cell/panel structural and electrical integration','D1-SOL-INTEG-001','Custom face-by-face integration and harness requirements for FLT-005 through FLT-008','Cell circuits to MPPT; deployer rails, camera field and antenna/switch clearance','Release six face drawings and exact panel variants; derive hot/cold Voc/current limits and require data for actual cells/coverglass/interconnects. Include diode/potting/retention parts if design requires them; no generic cell curves. Test continuity, insulation, IV response and mounting.',['S04','S22','E04'])
add('FLT-022','Wire/hardware retention, insulation and contamination control','D1-MAT-001','Custom controlled materials and application schedule','Harness, optics, panel, chassis and thermal-interface materials','Itemize manufacturer/product/lot for every tape, adhesive, coating and sleeve; specify cure, thickness, preparation and keep-outs. Retain outgassing/compatibility and process evidence, inspect coupons. 3M5413 sheet reports TML1.50%, CVCM0.50%; do not describe generic Kapton tape as space-qualified. Stycast resin needs its exact catalyst/process.',['E47','E50'],included='Constituents assigned to FLT-015/017/018/019/021, not duplicate mass')
add('FLT-023','Venting, service access and closeout identification','D1-CLOSEOUT-001','Custom closure/vent/access/label parts schedule','Structure pressure equalization, camera cover removal, RBF access and connector service','Define vent paths and obstruction controls, captive access covers if needed, label material and witness marks; prove no loose items or obstructed optics/antenna/rails. Establish ascent pressure requirement before vent verification. No new hole geometry claimed.',['S01','S33','S49'],included='Structure/integration constituent set, not an independent mass allocation')
add('SUP-001','Ground handling, charging and programming access','D1-EGSE-001','Custom spacecraft electrical ground-support interface and keyed test harness','Selected EPS service/charge port, OBC programming, safe power and telemetry','Release selected pinouts, isolation/fusing and keyed mating connectors. Use approved cell/pack charging behavior only; prevent launch inhibit defeat by EGSE. Verify polarity, no backfeed, safe reset and service disconnect. Include exact programmer hardware after OBC revision frozen.',['S03','S08','E25'])
add('SUP-002','Assembly support, transport and ESD protection','D1-HANDLING-001','Custom handling tray, restraints, covers and ESD workstation kit','1U frame, exposed panels/optics and service ports','Specify actual cradle/cover drawings, conductive/insulating materials, ESD mat/strap/tester SKUs and storage/shipping protections. Test restraint and clearance without loading cells or release hardware; define battery shipping requirements before shipment.',['S01','S33','S49'])
add('SUP-003','Conducted RF commissioning hardware','D1-RF-TEST-001','Custom attenuator/load/cable test kit and calibration plan','AX100 transmit/receive ports and ground RF chain','Select exact 50-ohm loads, DC blocks, attenuators, adapters and power ratings once frequency/power are frozen; calibrate complete chain, prove receiver input protection and transmitter load. Equipment rental/calibration is testing cost, not AI expense.',['S10','E31'])
add('SUP-004','Electrical/functional acceptance instrumentation and fixtures','D1-VERIFY-001','Custom verification fixture and instrument schedule','Supply rails, harnesses, deployment, image capture and reconstruction','Specify measurement uncertainty/range for DMM, scope/probes, electronic load, continuity/insulation tests and deployment capture. Select identifiable instruments before use; record calibration and exact fixture BOM. No invented test results; this is an unbuilt verification work package.',['S03','S08','S10','S49'])

# A better documented antenna challenger replaces the opaque family proposal,
# without being promoted through the evidence gate.
edit('FLT-012',manufacturer='Spacemanic',part='SAM-S, 5 V UHF configuration; exact tuned/order configuration unreleased',description='Proposed replacement for ISISPACE AntS family',sources=['E26','E37'],order_url=src['E37']['url'],dimensions_mass='98 x 98 x 6.2 mm bare; 10.1 mm including components; approximately 55 g',power='5 V; 0.075 W average, 1.5 W deployment per reviewed revision',interfaces='I2C/RS485 CSP v1; Molex 53261-0971 with mating housing 51021-0900; MMCX 73415-1000 RF port, example mate 73415-0950',uncertainty='Exact tuned frequency/order configuration, command dictionary, deployed swept geometry/pattern and application environmental evidence remain incomplete. Original PDF download failed; public web text reviewed. Not admitted.',blocked='Antenna release/control, link and clearance closure',cost='EUR 6,200 public page indication; not quoted as configured',rationale='Public SAM-S revision 4.2 supplies connector/pinout and mechanical detail missing from the earlier AntS family evidence. Better documented does not mean fully supported.',verification='Acquire exact current document bytes, check tuned variant and full command definitions, derive deployment envelope from controlled drawing and verify inhibited/redundant release. Integration with panel and cable requires new drawings, not silent CAD edits.')
edit('FLT-007',uncertainty='Existing AntS-specific panel concept no longer matches proposed SAM-S. Exact panel/antenna interface, mounting, mass and IV limits must be redesigned and documented.',rationale='Generation on the antenna face remains a project requirement; the old configured panel is not assumed compatible with the replacement antenna.')
edit('FLT-016',sources=['E26','S10'],uncertainty='AX100 MCX to SAM-S MMCX endpoints now identified at interface-family level; exact cable, connector configurations, length, bend radius, retention and measured loss absent.')
# Enrich every genuine custom part with a defined release path, without pretending detailed design exists.
specific={
'FLT-014':'Release schematic, regulator/protection IC BOM, layout and logic-level/backfeed analysis. Separate 5 V-derived regulated branches for OBC/radio and switched camera; prove voltage extrema below connected absolute maxima, current limit/retry behavior, thermal dissipation and single-fault containment with actual parts.',
'FLT-015':'Partition power, CAN/I2C/UART, switch/RBF and service harness branches; list every mating housing/contact/backshell and wire specification, gauge, length and termination. Require pin-to-pin drawing, continuity/insulation/voltage-drop tests, pull/strain-relief inspection and routing/bend/access review.',
'FLT-016':'AX100 MCX and proposed SAM-S MMCX endpoints are identified. Release exact 50-ohm cable, two connector part numbers and gender, length, bend/retention and workmanship; measure insertion/return loss at the authorized band against the existing <=1 dB assembly allocation.',
'FLT-017':'Design to piCAM/FM drawing and actual lens; release material/alloy/finish, M2.5 mating hardware, tolerances and baffle aperture. Verify retention, optical obstruction over field, fastener access, contamination and measured installed thermal path.',
'FLT-018':'Determine actual battery permitted temperature/charge conditions first. Release exact insulating/thermal material, thickness/area, compression/fasteners and surface preparation. Measure installed conductance and isolation across temperature; no generic conductance/density substituted.',
'FLT-019':'Create joint-by-joint fastener/standoff/washer/insert and bond-jumper schedule including manufacturer or drawing, alloy, length, thread engagement, locking method, torque and procurement quantity. Analyze joint loads and verify preload retention, bond continuity and access.',
'GND-006':'Separate static feedline, motion-rated flex loop, patch leads, adapters and weather seals. LMR-400 is only a static-run candidate; do not assume continuous-flex suitability. Freeze site lengths and endpoints, release exact cable/connector BOM, test installed loss/return loss, weather seals and full rotator travel.',
'GND-008':'Specify site, wind/ice/soil requirements, mast/foundation, nonconductive crossboom, anchors, bonds, entry surge protection and weather housing. Release drawings and exact hardware; independent structural/electrical review and installation inspection before use.'}
for r in rows:
 if r['id'] in specific:r['verification']=specific[r['id']]
 if r['status']=='CUSTOM/TO BE VERIFIED':
  r['design_state']='Requirements/work-package definition only; detailed design and constituent BOM not released'
  r['release_artifacts']=['Controlled drawing or schematic and interface pin map','Exact constituent BOM and material/process specifications','Analysis with source-backed properties and tolerances','Acceptance procedure with numerical criteria derived from connected equipment','As-built inspection and test record; independent review where required']
 else:r['design_state']='Manufacturer product proposal; not bought or tested'
 r['evidence_level']='DOCUMENTED' if r['status']=='SUPPORTED' else 'PROPOSED / DOCUMENTATION INCOMPLETE'
 r['mission_admitted']=False

counts=dict(collections.Counter(r['status'] for r in rows))
(O/'component_register.json').write_text(json.dumps(dict(document='D1-CMP-CLOSURE-001',date='2026-09-15',scope='Full proposed flight, ground and support set; unresolved exceptions retained honestly',gate='NOT CLOSED',counts=counts,items=rows),indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
out=['# Phase 1 consolidated proposed component register','', 'Revision A — 2026-09-15. **GATE NOT CLOSED. No complete spacecraft baseline is admitted.**','',f'{len(rows)} records: '+ '; '.join(f'{n} {k}' for k,n in counts.items())+'.','', '**SUPPORTED** means the specific component has adequate primary data for its stated bounded use; it does not establish the integrated installation, launch suitability or 12-month survival. **CUSTOM/TO BE VERIFIED** means a genuine custom work package, not fabricated design evidence. **CANDIDATE / EVIDENCE INCOMPLETE** is an explicit failed closure exception: the requested two-state end condition has not been reached. Removing this third state would conceal missing evidence.','', 'This register supersedes the 29-line operating proposal for the current review. It does not modify the controlled procurement BOM or authorize purchase. Alternative-only and included constituents are marked to avoid double counting. Unknown quantity, dimensions, mass, cost or current means unknown, never zero. No complete mass, power or cost total is defensible.','', 'Canonical data: `component_register.json`. Source IDs E01–E50 resolve in `source_index.md`; S identifiers resolve in `review/Source_Register.md` and `review/sources.json`. Archived manufacturer files stay local pending redistribution permission.','', '| ID | Function | Exact proposed part | State |','|---|---|---|---|']
for r in rows:out.append(f"| {r['id']} | {r['function']} | {r['part']} | {r['status']} |")
for r in rows:
 out+=['',f"## {r['id']} — {r['function']}",'']
 for key,label in [('status','State'),('manufacturer','Manufacturer/design authority'),('part','Part/configuration'),('quantity','Quantity'),('description','Description'),('included_in','Included/alternative relationship'),('dimensions_mass','Dimensions/mass'),('power','Power'),('interfaces','Interfaces'),('cost','Cost/availability'),('order_url','Order/reference route'),('rationale','Selection rationale'),('uncertainty','Remaining uncertainty'),('blocked','Blocked work'),('verification','Verification/release path'),('design_state','Design maturity')]:
  if r.get(key):out.append(f"- **{label}:** {r[key]}")
 out.append('- **Evidence:** '+', '.join(r['sources']))
 if 'release_artifacts'in r:out.append('- **Required release artifacts:** '+'; '.join(r['release_artifacts']))
(O/'component_register.md').write_text('\n'.join(out)+'\n',encoding='utf-8')
ix=['# Closure source index','', 'E identifiers are scoped to this closure review. Retrieval failures are preserved; a URL is not evidence of successful archival. Hashes identify the exact locally downloaded bytes, not independent validation of vendor claims. Document revisions should be checked in the linked document; do not infer a revision from the retrieval date.','', '| ID | Manufacturer document | Retrieval | SHA-256 |','|---|---|---|---|']
for s in sources:
 ix.append(f"| {s['id']} | [{s['title']}]({s['url']}) | {s['status']} ({s['retrieved_utc']}) | {s.get('sha256','NO ARCHIVED BYTES')} |")
 if s['status']=='RETRIEVED':
  (R/'SOURCES/components/closure_2026-09-15'/f"{s['id']}.url").write_text('[InternetShortcut]\nURL='+s['url']+'\n',encoding='utf-8')
ix+=['','Public web text was additionally reviewed for E03–E06, E24–E26 and current product pages E34–E41 where accessible; failed original downloads do not acquire hashes from that review. E16 is a Japanese manual and is not credited as a fully reviewed English command specification. E01/E02 current revisions were not obtained; older E24/E25 cannot silently stand in for them.','', 'The archive manifest retains retrieval time, exact URL, result, bytes and hash. No new authoritative qualification evidence was produced by this research.']
(O/'source_index.md').write_text('\n'.join(ix)+'\n',encoding='utf-8')
print(json.dumps(counts));print(len(rows))

